[phases.setup]
nixPkgs = ["nodejs-18_x", "python310"]

[phases.install]
cmds = [
    "npm install",
    "cp -r Gau/backend backend",
    "pip install -r backend/requirements.txt",
    "pip install gunicorn"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cp -r dist backend/static && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile - --chdir backend app:app"
