[phases.setup]
nixPkgs = ["nodejs-18_x", "python310"]

[phases.install]
cmds = [
    "npm install",
    "pip install -r Gau/backend/requirements.txt",
    "pip install gunicorn"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "sh -c 'cp -r dist Gau/backend/static && cd Gau/backend && gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --access-logfile - --error-logfile - app:app'"
